version: 2
jobs:
  build:
    working_directory: ~/repo
    environment:
          # Customize the JVM maximum heap limit
          MAVEN_OPTS: -Xmx3200m
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn package
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
