version: 2
jobs:
  build:
    working_directory: ~/jacobwortmann
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn package
  deploy:
      machine:
        enabled: true
      working_directory: ~/jacobwortmann
      steps:
        - run:
            command: |
              scp ./target/jacobwortmann-webapp.war jacob@jacobwortmann.dk:~/Programs/wlp-openliberty/usr/servers/electro/apps/
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
