version: 2
jobs:
  build:
    working_directory: ~/jacobwortmann
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: jacobwortmann-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: jacobwortmann-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/jacobwortmann-webapp.war
  deploy:
    machine:
        enabled: true

    working_directory: ~/jacobwortmann

    environment:
       # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          command: |
            ssh-keyscan -H jacobwortmann.dk >> ~/.ssh/known_hosts
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              scp target/jacobwortmann-webapp.war jacob@jacobwortmann.dk:~/Programs/wlp-openliberty/usr/servers/electro/apps/
            fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
