defaults:
  working_directory: ~/jacobwortmann

version: 2
jobs:
  build:
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: jacobwortmann-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: jacobwortmann-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/jacobwortmann-webapp.war
      - persist_to_workspace:
          root: target
          paths:
            - jacobwortmann-webapp.war

  deploy:
    machine:
        enabled: true
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: target
      - run:
          command: |
            cd target
            ssh-keyscan -H jacobwortmann.dk >> ~/.ssh/known_hosts
            scp jacobwortmann-webapp.war jacob@jacobwortmann.dk:~/Programs/wlp-openliberty/usr/servers/electro/apps/
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
